AWSTemplateFormatVersion: 2010-09-09
Description: Provision cloud resources

Parameters: 
  Env:
    Description: Deployment Environment
    Type: String
  KeyName:
    Description:  ssh Keyname for the instance 
    Type: String
  InstanceImageId:
    Description: Image ID for creating Ec2 instance
    Type: AWS::EC2::Image::Id
  InstanceType:
    Description: Instance Type of the server
    Type: String
Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref KeyName
      ImageId: !Ref InstanceImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: !Sub ${Env}-Server-Instance
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group of the ec2 instance
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${Env}-Security-Group
